name: "DAST with Nuclei"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: secopslab/nuclei-action@v1
        with:
          urls-txt: ".github/nuclei.txt"
          custom-templates: ".github/custom-templates/"
          user-agent: "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"

      - uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - uses: secopslab/appsec-etl@v1
        with:
          tool: nuclei
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_NUCLEI }}
          datadog-token: ${{ secrets.DATADOG_TOKEN }}
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram-channel: ${{secrets.TELEGRAM_CHANNEL }}
